package samples.quickstart;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.cxf.annotations.DataBinding;
import org.apache.cxf.jibx.JiBXDataBinding;

/**
 * This class was generated by Apache CXF 2.3.0-SNAPSHOT
 * Wed Aug 11 20:49:19 IST 2010
 * Generated source version: 2.3.0-SNAPSHOT
 * 
 */
 
@WebService(targetNamespace = "http://quickstart.samples/", name = "StockQuoteServicePortType")
@DataBinding( value = JiBXDataBinding.class)
public interface StockQuoteServicePortType {

    @Oneway
    @RequestWrapper(localName = "update", targetNamespace = "http://quickstart.samples/xsd", className = "samples.quickstart.xsd.Update")
    @WebMethod(action = "urn:update")
    public void update(
        @WebParam(name = "symbol", targetNamespace = "http://quickstart.samples/xsd")
        java.lang.String symbol,
        @WebParam(name = "price", targetNamespace = "http://quickstart.samples/xsd")
        java.lang.Double price
    );

    
    @ResponseWrapper(localName = "getPriceResponse", targetNamespace = "http://quickstart.samples/xsd", className = "samples.quickstart.xsd.GetPriceResponse")
    @RequestWrapper(localName = "getPrice", targetNamespace = "http://quickstart.samples/xsd", className = "samples.quickstart.xsd.GetPrice")
    @WebResult(name = "return", targetNamespace = "http://quickstart.samples/xsd")
    @WebMethod(action = "urn:getPrice")
    public java.lang.Double getPrice(
        @WebParam(name = "symbol", targetNamespace = "http://quickstart.samples/xsd")
        java.lang.String symbol
    );
}
