
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package samples.quickstart;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.0-SNAPSHOT
 * Wed Aug 11 20:49:19 IST 2010
 * Generated source version: 2.3.0-SNAPSHOT
 * 
 */

@javax.jws.WebService(
                      serviceName = "StockQuoteService",
                      portName = "StockQuoteServiceSOAP11port",
                      targetNamespace = "http://quickstart.samples/",
                      wsdlLocation = "file:/home/nilupa/Documents/experiment/StockQuoteService.wsdl",
                      endpointInterface = "samples.quickstart.StockQuoteServicePortType")
                      
public class StockQuoteServicePortTypeImpl implements StockQuoteServicePortType {

    private static final Logger LOG = Logger.getLogger(StockQuoteServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see samples.quickstart.StockQuoteServicePortType#update(java.lang.String  symbol ,)java.lang.Double  price )*
     */
    public void update(java.lang.String symbol,java.lang.Double price) { 
        LOG.info("Executing operation update");
        System.out.println(symbol);
        System.out.println(price);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see samples.quickstart.StockQuoteServicePortType#getPrice(java.lang.String  symbol )*
     */
    public java.lang.Double getPrice(java.lang.String symbol) { 
        LOG.info("Executing operation getPrice");
        System.out.println(symbol);
        try {
            java.lang.Double _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
