
/*
 * 
 */

package samples.quickstart;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.0-SNAPSHOT
 * Wed Aug 11 20:49:19 IST 2010
 * Generated source version: 2.3.0-SNAPSHOT
 * 
 */


@WebServiceClient(name = "StockQuoteService", 
                  wsdlLocation = "file:/home/nilupa/Documents/experiment/StockQuoteService.wsdl",
                  targetNamespace = "http://quickstart.samples/") 
public class StockQuoteService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://quickstart.samples/", "StockQuoteService");
    public final static QName StockQuoteServiceSOAP11Port = new QName("http://quickstart.samples/", "StockQuoteServiceSOAP11port");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/nilupa/Documents/experiment/StockQuoteService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/home/nilupa/Documents/experiment/StockQuoteService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public StockQuoteService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StockQuoteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockQuoteService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public StockQuoteService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public StockQuoteService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StockQuoteService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StockQuoteServicePortType
     */
    @WebEndpoint(name = "StockQuoteServiceSOAP11port")
    public StockQuoteServicePortType getStockQuoteServiceSOAP11Port() {
        return super.getPort(StockQuoteServiceSOAP11Port, StockQuoteServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockQuoteServicePortType
     */
    @WebEndpoint(name = "StockQuoteServiceSOAP11port")
    public StockQuoteServicePortType getStockQuoteServiceSOAP11Port(WebServiceFeature... features) {
        return super.getPort(StockQuoteServiceSOAP11Port, StockQuoteServicePortType.class, features);
    }

}
